### ISSUE TITLE
Mobile Group ve Event show error

### ISSUE THREAD

**Issue by BurakYilmaz92** [bounswe/bounswe2015group3#249]
Event in show için alınan hata 
12-14 09:37:50.638 12853-12853/com.group3.cmpesocial E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.group3.cmpesocial/com.group3.cmpesocial.activities.event.EventDetailActivity}: java.lang.ClassCastException: android.support.v7.widget.AppCompatImageButton cannot be cast to android.widget.Button
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2092)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
                                                                           at android.app.ActivityThread.access$700(ActivityThread.java:134)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4867)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.ClassCastException: android.support.v7.widget.AppCompatImageButton cannot be cast to android.widget.Button
                                                                           at com.group3.cmpesocial.activities.event.EventDetailActivity.onCreate(EventDetailActivity.java:140)
                                                                           at android.app.Activity.performCreate(Activity.java:5047)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117) 
                                                                           at android.app.ActivityThread.access$700(ActivityThread.java:134) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:137) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4867) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774) 
                                                                           at dalvik.system.NativeStart.main(Native Method) 
12-14 09:39:07.686 12853-12853/com.group3.cmpesocial I/Process: Sending signal. PID: 12853 SIG: 9

---

Group show için alınan hata :
12-14 09:41:17.456 14846-14846/com.group3.cmpesocial E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.group3.cmpesocial/com.group3.cmpesocial.activities.group.GroupDetailActivity}: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2092)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
                                                                           at android.app.ActivityThread.access$700(ActivityThread.java:134)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4867)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException

**Comment by BurakYilmaz92** [comment]
Tests are on going.
