### ISSUE TITLE
mobile-register new user

### ISSUE THREAD

**Issue by BurakYilmaz92** [bounswe/bounswe2015group3#251]
12-14 10:10:23.682 28048-28048/com.group3.cmpesocial E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.group3.cmpesocial/com.group3.cmpesocial.activities.SignupActivity}: java.lang.RuntimeException: setOnItemClickListener cannot be used with a spinner.
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2092)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117)
                                                                           at android.app.ActivityThread.access$700(ActivityThread.java:134)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4867)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.RuntimeException: setOnItemClickListener cannot be used with a spinner.
                                                                           at android.widget.Spinner.setOnItemClickListener(Spinner.java:427)
                                                                           at com.group3.cmpesocial.activities.SignupActivity.onCreate(SignupActivity.java:44)
                                                                           at android.app.Activity.performCreate(Activity.java:5047)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117) 
                                                                           at android.app.ActivityThread.access$700(ActivityThread.java:134) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:137) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4867) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774) 
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by BurakYilmaz92** [comment]
Test are done. It works well
